### PR TITLE
Tasks and submissions

### LINKED ISSUE #18: Task model in database
Task model:
```
id String @id() @default(uuid())
name String
description String
team Team

teamid String
```

### LINKED ISSUE #19: Create new task
Be able to call an endpoint to create a new task for a team in the database.
It should validate the input and also check if the user has TEACHER permission in that team.

### LINKED ISSUE #20: List all task in a team
Be able to list all of the tasks in a team by calling the `GET /team/:id/task` endpoint.
The endpoint should validate if the user is a member in the team.

### LINKED ISSUE #24: Team details page (/team/:id)
This page should have a title with the team's name and two buttons: "Members" and "Create new task"

Under these, there should be a Grid of Cards, with the list of tasks in the team.  
The cards should have an open button that dericts to the following link: `/team/:teamID/task/:taskID`

### LINKED ISSUE #26: Task creation dialog
This dialog should have one textfield for the title and one bigger for the description.
Both of them can only be plain texts for simplicity.

Under them, there should be a [Select](https://mui.com/material-ui/react-select/#main-content) with options for C and another option for C++.

And under them, there should be another Textfield for a script that tests out the student's submissions.

### LINKED ISSUE #27: List of all tasks in a team
We should be able to view all of the tasks in a team. The details should not be here, only a brief recap (e.g: name of the task, a preview of the description, the number of submissions, etc.).

### LINKED ISSUE #28: List of all submissions to a task
By clicking on a task, we should be able to view all of the submissions for a given task.
This would mean that both the teacher and the student would see the same page, except the teacher would see who submitted it.

### LINKED ISSUE #34: Submission model
Submission model:
```
id String @id @default(uuid())
createdAt Date @defalt(now())
status Status
files File[]
user User
task Task

userid String
taskid String
```

Status: `RUNNING` / `SUCCESS` / `FAILED`

Question: What else could we include in this model?

### LINKED ISSUE #35: Send submission to a task
The backend should be able to receive files sent by the frontend as plain text and be able to run them in a Docker container while watching the logs and writing it to the database.

### LINKED ISSUE #36: List all submissions to a task
There should be an endpoint where we list all of the submissions to a given task. As the teacher, this endpoint would send back an additional id for the student.

### LINKED ISSUE #39: Update the submission status after Docker container exits
Update the submission's status depending on the exit code of the Docker container.

### PR DESCRIPTION
**Pull request by pepyta**
This PR will add the functionality to create a new task (closes #19), list tasks (closes #20), list submissions for a task (#33), and submit a new solution (#29).

Also, closes #34, closes #18, closes #24, closes #26, closes #27, closes #28, closes #26, closes #39, closes #36, closes #35.

### CODE REVIEW

**Comment by pepyta** [comment]
@TuguldurSosorbaram as I can see, you have the #38 issue. You can create a new branch based on this PR to start on working on it.

**Comment by pepyta** [comment]
@TuguldurSosorbaram as I can see, you have the #38 issue. You can create a new branch based on this PR to start on working on it.

**Comment by pepyta** [comment]
Also closes #26, closes #39, closes #36, closes #35.

**Review by 2976579765 — APPROVED** [review]
Tested working

**Pull request merged**
